WebUI/Blog.WebUI.Site/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Models
{
    public class CategoryViewModel
    {
        public CategoryViewModel()
        {
            Category = new Model.Category();
            Contents = new List<Model.Content>();
        }

        public Model.Category Category { get; set; }
        public List<Model.Content> Contents { get; set; }

        public int CurrentPage { get; set; }
        public int TotalData { get; set; }
        public double TotalPage { get; set; }
    }
}

WebUI/Blog.WebUI.Site/Models/ContentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Models
{
    public class ContentViewModel
    {
        public ContentViewModel()
        {
            Content = new Model.Content();
            Relateds = new List<Model.Content>();
        }

        public Model.Content Content { get; set; }
        public List<Model.Content> Relateds { get; set; }
      
    }
}

WebUI/Blog.WebUI.Site/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Models
{
    public class HomeViewModel
    {
    }
}

WebUI/Blog.WebUI.Site/Controllers/CategoryController.cs
using Blog.Data;
using Blog.WebUI.Site.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Controllers
{
    public class CategoryController:Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;
        ContentCategoryData _contentCategoryData;

        public CategoryController(CategoryData _categoryData, ContentData _contentData, ContentCategoryData _contentCategoryData)
        {
            this._categoryData = _categoryData;
            this._contentData = _contentData;
            this._contentCategoryData = _contentCategoryData;
        }
        public IActionResult Index(string slug, int page = 1)
        {
            var category = _categoryData.GetBy(x => x.Slug == slug && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "kategori-bulunamadi" });

            var category_content_ids = _contentCategoryData.GetByPage(x => x.CategoryId == category.Id, page, 10)
                .Select(x => x.ContentId).ToList();
            var total_data = _contentCategoryData.GetCount(x => x.CategoryId == category.Id);
            double c = double.Parse(total_data.ToString()) / 10;
            c = Math.Ceiling(c);

            var contents = _contentData.GetContentsByIds(category_content_ids, 10);

            var model = new CategoryViewModel()
            {
                Category = category,
                Contents = contents,
                CurrentPage = page,
                TotalData = total_data,
                TotalPage = c,
            };

            return View(model);
        }
    
    }
}

WebUI/Blog.WebUI.Site/Controllers/ContentController.cs
using Blog.Data;
using Blog.WebUI.Site.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Controllers
{
    public class ContentController : Controller
    {
        ContentData _contentData;
        ContentCategoryData _contentCategoryData;

        public ContentController(ContentData _contentData, ContentCategoryData _contentCategoryData)
        {
            this._contentData = _contentData;
            this._contentCategoryData = _contentCategoryData;
        }
        public IActionResult Index(string slug)
        {
            var content = _contentData.GetContentBySlug(slug);
            if (content == null)
                return RedirectToAction("Index", "Home", new { q = "makale-bulunamadi" });

            var category = _contentCategoryData.GetBy(x => x.ContentId == content.Id).FirstOrDefault();
            var relateds = new List<Model.Content>();

            if (category != null)
            {
                var category_content_ids = _contentCategoryData.GetBy(x => x.CategoryId == category.Id)
                .Take(6).Select(x => x.ContentId).ToList();

                relateds = _contentData.GetContentsByIds(category_content_ids, 6);
            }
            else
            {
                var dtNow = DateTime.Now;
                relateds = _contentData.GetBy(x => x.IsActive && !x.IsDeleted && x.PublishDate <= dtNow);
            }

            var model = new ContentViewModel()
            {
                Content = content,
                Relateds = relateds,
            };

            return View(model);
        }
    }
}

WebUI/Blog.WebUI.Site/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Site.Controllers
{
    public class HomeController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebUI/Blog.WebUI.Site/Views/Category/Index.cshtml
@model CategoryViewModel
@{
    ViewBag.Title = "Kategori";
}
<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@Model.Category.Name</div>
                </div>
                @foreach (var item in Model.Contents)
                {
                    <div class="row pb-4">
                        <div class="col-md-5">
                            <div class="fh5co_hover_news_img">
                                <div class="fh5co_news_img">
                                    @if (item.Media != null)
                                    {
                                        <img src="@item.Media.MediaUrl" alt="" />
                                    }
                                    else
                                    {
                                        <img src="images/nathan-mcbride-229637.jpg" alt="" />
                                    }
                                </div>
                                <div></div>
                            </div>
                        </div>
                        <div class="col-md-7 animate-box">
                            <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="fh5co_magna py-2">
                                @item.Title
                            </a> <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="fh5co_mini_time py-3">
                                @if (item.Author != null)
                                {
                                    @item.Author.Fullname <span>-</span>
                                }
                                @item.PublishDate.ToString("dd MMMM yyyy")
                            </a>

                            <div class="fh5co_consectetur">
                                @item.MetaDescription
                            </div>
                        </div>
                    </div>
                }

            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    <a href="#" class="fh5co_tagg">Business</a>
                    <a href="#" class="fh5co_tagg">Technology</a>
                    <a href="#" class="fh5co_tagg">Sport</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                    <a href="#" class="fh5co_tagg">Photography</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Education</a>
                    <a href="#" class="fh5co_tagg">Social</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                </div>
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/download (1).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/allef-vinicius-108153.jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Enim ad minim veniam nostrud xercitation ullamco.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/download (2).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/seth-doyle-133175.jpg" alt="img"
                             class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
            </div>
        </div>
        @if (Model.TotalPage > 1)
        {
            <div class="row mx-0">
                <div class="col-12 text-center pb-4 pt-4">

                    @if (Model.CurrentPage == 1)
                    {
                        var next = Model.CurrentPage + 1;
                        <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                        <a href="@Url.Action("Index","Category", new { page = next, slug = Model.Category.Slug })" class="btn_mange_pagging">İleri <i class="fa fa-long-arrow-right"></i></a>
                    }
                    else
                    {
                        if (Model.TotalPage > Model.CurrentPage)
                        {
                            var next = Model.CurrentPage + 1;
                            var prev = Model.CurrentPage - 1;

                            <a href="@Url.Action("Index","Category", new { page = prev, slug = Model.Category.Slug })" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i> Geri</a>
                            <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                            <a href="@Url.Action("Index","Category", new { page = next, slug = Model.Category.Slug })" class="btn_mange_pagging">İleri <i class="fa fa-long-arrow-right"></i></a>
                        }
                        else
                        {
                            var prev = Model.CurrentPage - 1;

                            <a href="@Url.Action("Index","Category", new { page = prev, slug = Model.Category.Slug })" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i> Geri</a>
                            <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>

WebUI/Blog.WebUI.Site/Views/Content/Index.cshtml
@model ContentViewModel
@{
    ViewBag.Title = "Makale";
    var media = Model.Content.Media;
}
<div id="fh5co-title-box" style="background-image: url(@Html.Raw(media!=null ? media.MediaUrl :"/_assets/images/camila-cordeiro-114636.jpg" )); background-position: 50% 90.5px;" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="page-title">
        <img src="~/assets/images/person_1.jpg" alt="Free HTML5 by FreeHTMl5.co">
        <span>@Model.Content.PublishDate.ToString("dd MMMM yyyy")</span>
        <h2>@Model.Content.Title</h2>
    </div>
</div>
<div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">                
                @Html.Raw(Model.Content.Description)               
            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    <a href="#" class="fh5co_tagg">Business</a>
                    <a href="#" class="fh5co_tagg">Technology</a>
                    <a href="#" class="fh5co_tagg">Sport</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                    <a href="#" class="fh5co_tagg">Photography</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Education</a>
                    <a href="#" class="fh5co_tagg">Social</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                </div>
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/download (1).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/allef-vinicius-108153.jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Enim ad minim veniam nostrud xercitation ullamco.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/download (2).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="images/seth-doyle-133175.jpg" alt="img"
                             class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebUI/Blog.WebUI.Site/Views/Home/Index.cshtml
@model HomeViewModel
@{ ViewBag.Title = "Ana Sayfa"; }
<div class="container-fluid paddding mb-5">
    <div class="row mx-0">
        <div class="col-md-6 col-12 paddding animate-box" data-animate-effect="fadeIn">
            @foreach (var item in cache.NewContents.Take(1))
             {
                <div class="fh5co_suceefh5co_height">
                @if (item.Media != null)
                {
                    <img src="@item.Media.MediaUrl" alt="img" /> }
                else
                {
                    <img src="~/_assets/images/nick-karvounis-78711.jpg" alt="img" />
                }
                <div class="fh5co_suceefh5co_height_position_absolute"></div>
                <div class="fh5co_suceefh5co_height_position_absolute_font">
                <div class="">
                    <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="color_fff">
                        <i class="fa fa-clock-o"></i>@item.PublishDate.ToString("dd MMMM yyyy")
                    </a>
                </div>
                <div class=""><a href="single.html" class="fh5co_good_font"> @item.Title </a></div>
                </div>
                </div>       
             }
        </div>
        <div class="col-md-6">
            <div class="row">
                @foreach (var item in cache.NewContents.Skip(1).Take(4))
                {
    <div class="col-md-6 col-6 paddding animate-box" data-animate-effect="fadeIn">
        <div class="fh5co_suceefh5co_height_2">
            @if (item.Media != null)
            {
<img src="@item.Media.MediaUrl" alt="img" /> }
                else
                {
<img src="~/_assets/images/science-578x362.jpg" alt="img" />}

            <div class="fh5co_suceefh5co_height_position_absolute"></div>
            <div class="fh5co_suceefh5co_height_position_absolute_font_2">
                <div class="">
                    <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="color_fff">
                        <i class="fa fa-clock-o"></i>&nbsp;&nbsp;Oct
                        @item.PublishDate.ToString("dd MMMM yyyy")
                    </a>
                </div>
                <div class=""><a href="single.html" class="fh5co_good_font_2"> @item.Title </a></div>
            </div>
        </div>
    </div>}

            </div>
        </div>
    </div>
</div>

<div class="container-fluid pt-3">
    <div class="container animate-box" data-animate-effect="fadeIn">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Trending</div>
        </div>
        <div class="owl-carousel owl-theme js" id="slider1">
            @foreach (var item in cache.NewContents.Skip(5).Take(8))
            {
<div class="item px-2">
    <div class="fh5co_latest_trading_img_position_relative">
        <div class="fh5co_latest_trading_img">
            @if (item.Media != null)
            {
<img src="@item.Media.MediaUrl" alt="@item.Media.Alt" class="fh5co_img_special_relative" /> }
                else
                {
<img src="~/_assets/images/allef-vinicius-108153.jpg" alt=""
     class="fh5co_img_special_relative" />}

        </div>
        <div class="fh5co_latest_trading_img_position_absolute"></div>
        <div class="fh5co_latest_trading_img_position_absolute_1">
            <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="text-white"> @item.Title </a>
            <div class="fh5co_latest_trading_date_and_name_color">
                @if (item.Author != null)
                {
                     @item.Author.Fullname <span>-</span>
                }  -  @item.PublishDate.ToString("dd MMMM yyyy")
            </div>
        </div>
    </div>
</div>            }
        </div>
    </div>
</div>

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Son Eklenenler</div>
                </div>
                @foreach (var item in cache.NewContents.Skip(13).Take(12))
                {
    <div class="row pb-4">
        <div class="col-md-5">
            <div class="fh5co_hover_news_img">
                <div class="fh5co_news_img">
                    @if (item.Media != null)
                    {
    <img src="@item.Media.MediaUrl" alt="@item.Media.Alt" /> }
                    else
                    {
    <img src="~/_assets/images/nathan-mcbride-229637.jpg" alt="" />}
                </div>
                <div></div>
            </div>
        </div>
        <div class="col-md-7 animate-box">
            <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="fh5co_magna py-2">
                @item.Title
            </a> <a href="@Url.Action("Index","Content",new { slug = item.Slug})" class="fh5co_mini_time py-3">
                @if (item.Author != null)
                {
                    @item.Author.Fullname <span>-</span>
                } 
                - @item.PublishDate.ToString("dd MMMM yyyy")
            </a>

            <div class="fh5co_consectetur">
                Amet consectetur adipisicing elit, sed do eiusmod tempor incididunt
                ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
            </div>
        </div>
    </div>}

            </div>
            <div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
                </div>
                <div class="clearfix"></div>
                <div class="fh5co_tags_all">
                    <a href="#" class="fh5co_tagg">Business</a>
                    <a href="#" class="fh5co_tagg">Technology</a>
                    <a href="#" class="fh5co_tagg">Sport</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                    <a href="#" class="fh5co_tagg">Photography</a>
                    <a href="#" class="fh5co_tagg">Lifestyle</a>
                    <a href="#" class="fh5co_tagg">Art</a>
                    <a href="#" class="fh5co_tagg">Education</a>
                    <a href="#" class="fh5co_tagg">Social</a>
                    <a href="#" class="fh5co_tagg">Three</a>
                </div>
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom pt-3 py-2 mb-4">Most Popular</div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="~/_assets/images/download (1).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="~/_assets/images/allef-vinicius-108153.jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Enim ad minim veniam nostrud xercitation ullamco.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="~/_assets/images/download (2).jpg" alt="img" class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
                <div class="row pb-3">
                    <div class="col-5 align-self-center">
                        <img src="~/_assets/images/seth-doyle-133175.jpg" alt="img"
                             class="fh5co_most_trading" />
                    </div>
                    <div class="col-7 paddding">
                        <div class="most_fh5co_treding_font"> Magna aliqua ut enim ad minim veniam quis nostrud.</div>
                        <div class="most_fh5co_treding_font_123"> April 18, 2016</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mx-0 animate-box" data-animate-effect="fadeInUp">
            <div class="col-12 text-center pb-4 pt-4">
                <a href="#" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i>&nbsp;&nbsp; Previous</a>
                <a href="#" class="btn_pagging">1</a>
                <a href="#" class="btn_pagging">2</a>
                <a href="#" class="btn_pagging">3</a>
                <a href="#" class="btn_pagging">...</a>
                <a href="#" class="btn_mange_pagging">Next <i class="fa fa-long-arrow-right"></i>&nbsp;&nbsp; </a>
            </div>
        </div>
    </div>
</div>